name: elnozom_pda
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.6
  flutter: 
    sdk: flutter
  flutter_form_builder: ^6.0.1
  shared_preferences: ^2.0.6
  simple_autocomplete_formfield: ^0.3.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/home-bg.png
    - assets/images/logo.png

  fonts:
    - family: Frutiger
      fonts:
        - asset: assets/fonts/Frutiger.ttf

